### ISSUE TITLE
readBean() needs javadocs on EOF handling

### ISSUE THREAD

**Issue by j256** [42BV/CSVeed#52] opened 2014-11-21 18:46 UTC
Right now BeanReader.readBean() and CsvClient.readBean() don't have any information about how to detect EOF.  Should be:

```
 @return Bean read from the reader or null on EOF.
```

Thanks.

**Comment by hazendaz** [comment] 2023-06-12 03:04
closing as duplicate of javadoc issues on https://github.com/42BV/CSVeed/issues/50.  Will be looking at all and will review this again as it will now be linked.

**Closed by hazendaz** 2023-06-12 03:04 UTC
